# Generated by Django 5.1.3 on 2024-11-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plex_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plexserverconnection",
            name="direct_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="plexserverconnection",
            name="local_url",
            field=models.URLField(blank=True),
        ),
    ]
