# Generated by Django 5.1.3 on 2024-11-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plex_auth", "0002_alter_plexuser_options_alter_plexuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plexserver",
            options={
                "verbose_name": "Plex Server",
                "verbose_name_plural": "Plex Servers",
            },
        ),
    ]
