# Generated by Django 5.1.3 on 2024-12-01 01:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plex_auth", "0002_plexserverconnection_direct_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plex_key", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("duration", models.IntegerField(help_text="Duration in milliseconds")),
                ("content_rating", models.CharField(blank=True, max_length=10)),
                ("video_resolution", models.CharField(blank=True, max_length=20)),
                ("studio", models.CharField(blank=True, max_length=100)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("genres", models.JSONField(blank=True, default=list)),
                ("directors", models.JSONField(blank=True, default=list)),
                ("actors", models.JSONField(blank=True, default=list)),
                ("added_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("thumb_url", models.URLField(blank=True, max_length=1024)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="plex_auth.plexserverconnection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["server", "plex_key"],
                        name="media_manag_server__64b5a6_idx",
                    ),
                    models.Index(fields=["title"], name="media_manag_title_deed43_idx"),
                    models.Index(fields=["year"], name="media_manag_year_de05af_idx"),
                    models.Index(
                        fields=["content_rating"], name="media_manag_content_cb06ac_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="media_manag_rating_9feb54_idx"
                    ),
                    models.Index(
                        fields=["duration"], name="media_manag_duratio_f5f8ce_idx"
                    ),
                    models.Index(
                        fields=["added_at"], name="media_manag_added_a_e6e9cb_idx"
                    ),
                ],
                "unique_together": {("server", "plex_key")},
            },
        ),
    ]
